# SPRING PROPERTIES
spring:
  application:
    name: auth-server
  profiles:
    active: local

server:
  port: 8082

# EUREKA PROPERTIES 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/